/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.za.kroutled.view;

import co.za.kroutled.Utilities.Writer;
import co.za.kroutled.controller.Battle;
import co.za.kroutled.controller.Loadgame;
import co.za.kroutled.model.Map;
import co.za.kroutled.model.characters.*;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author kyle
 */
public class Window extends javax.swing.JFrame {

    public Hero myHero;
    private static Enemy foundEnemy = null;
    Map map;
    Loadgame load = new Loadgame();
    Battle fight = new Battle();
    CardLayout card;

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
        card =  (CardLayout)MainPanel.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        heroes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        winText = new javax.swing.JTextArea();
        MainPanel = new javax.swing.JPanel();
        StartPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        CreatePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        inputName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        SelectPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        heroList = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        selectedHero = new javax.swing.JTextField();
        selectButton = new javax.swing.JButton();
        GamePanel = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Map = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        Sim = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        gameStats = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fightRunPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        fightButton = new javax.swing.JButton();
        runButton = new javax.swing.JButton();
        equipDiscard = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        equipButton = new javax.swing.JButton();
        discardButton = new javax.swing.JButton();
        winPanel = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        winText1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        heroes.setText("jLabel7");
        heroes.getAccessibleContext().setAccessibleName("heroes");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane5.setViewportView(jTextArea1);

        winText.setColumns(20);
        winText.setRows(5);
        jScrollPane6.setViewportView(winText);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Welcome to the World");

        jLabel4.setText("Would you like to:");

        jButton2.setText("Create Hero");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Select Hero");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout StartPanelLayout = new javax.swing.GroupLayout(StartPanel);
        StartPanel.setLayout(StartPanelLayout);
        StartPanelLayout.setHorizontalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(StartPanelLayout.createSequentialGroup()
                                .addGroup(StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton2)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10))))
                    .addGroup(StartPanelLayout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(301, Short.MAX_VALUE))
        );
        StartPanelLayout.setVerticalGroup(
            StartPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StartPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(237, Short.MAX_VALUE))
        );

        MainPanel.add(StartPanel, "startPanel");

        jLabel2.setText("Create your hero:");

        jLabel5.setText("Enter your hero's name:");

        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });

        jLabel6.setText("What class is your hero:");

        jButton4.setText("Druid");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Mage");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Warrior");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreatePanelLayout = new javax.swing.GroupLayout(CreatePanel);
        CreatePanel.setLayout(CreatePanelLayout);
        CreatePanelLayout.setHorizontalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CreatePanelLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(CreatePanelLayout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(344, Short.MAX_VALUE))
        );
        CreatePanelLayout.setVerticalGroup(
            CreatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreatePanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(35, 35, 35)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(47, 47, 47))
        );

        MainPanel.add(CreatePanel, "createPanel");

        jLabel3.setText("Select your hero:");

        heroList.setColumns(20);
        heroList.setRows(5);
        jScrollPane4.setViewportView(heroList);

        jLabel7.setText("Enter your hero's number below:");

        selectButton.setText("Select Hero");
        selectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectPanelLayout = new javax.swing.GroupLayout(SelectPanel);
        SelectPanel.setLayout(SelectPanelLayout);
        SelectPanelLayout.setHorizontalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addGroup(SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(selectedHero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SelectPanelLayout.createSequentialGroup()
                        .addGap(293, 293, 293)
                        .addComponent(selectButton)))
                .addContainerGap(319, Short.MAX_VALUE))
        );
        SelectPanelLayout.setVerticalGroup(
            SelectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(selectButton)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        MainPanel.add(SelectPanel, "selectPanel");

        jButton7.setText("North");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("West");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("East");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("South");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(Map);
        Map.getAccessibleContext().setAccessibleName("");

        jScrollPane2.setViewportView(Sim);

        jScrollPane3.setViewportView(gameStats);

        jLabel8.setText("Stats");

        jLabel9.setText("Simulator");

        jLabel10.setText("Map");

        javax.swing.GroupLayout GamePanelLayout = new javax.swing.GroupLayout(GamePanel);
        GamePanel.setLayout(GamePanelLayout);
        GamePanelLayout.setHorizontalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(74, 74, 74)
                        .addComponent(jButton9))
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jButton10))
                    .addGroup(GamePanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton7)))
                .addGap(262, 262, 262))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel8)
                .addGap(203, 203, 203)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(126, 126, 126))
        );
        GamePanelLayout.setVerticalGroup(
            GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GamePanelLayout.createSequentialGroup()
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2))
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(GamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10)
                .addContainerGap())
        );

        MainPanel.add(GamePanel, "gamePanel");

        jLabel11.setText("An enemy has appeared and challenges you to battle");

        jLabel12.setText("What will you do?");

        fightButton.setText("Fight");
        fightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightButtonActionPerformed(evt);
            }
        });

        runButton.setText("Run");
        runButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fightRunPanelLayout = new javax.swing.GroupLayout(fightRunPanel);
        fightRunPanel.setLayout(fightRunPanelLayout);
        fightRunPanelLayout.setHorizontalGroup(
            fightRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightRunPanelLayout.createSequentialGroup()
                .addGroup(fightRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fightRunPanelLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fightRunPanelLayout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fightRunPanelLayout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(fightRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fightButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(runButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        fightRunPanelLayout.setVerticalGroup(
            fightRunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fightRunPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(fightButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(runButton)
                .addContainerGap(298, Short.MAX_VALUE))
        );

        MainPanel.add(fightRunPanel, "fightRunPanel");

        jLabel13.setText("It would appear that the enemy has dropped something!");

        jLabel14.setText("Would you like to:");

        equipButton.setText("Equip");
        equipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipButtonActionPerformed(evt);
            }
        });

        discardButton.setText("Discard");
        discardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout equipDiscardLayout = new javax.swing.GroupLayout(equipDiscard);
        equipDiscard.setLayout(equipDiscardLayout);
        equipDiscardLayout.setHorizontalGroup(
            equipDiscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipDiscardLayout.createSequentialGroup()
                .addGroup(equipDiscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(equipDiscardLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel14))
                    .addGroup(equipDiscardLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel13))
                    .addGroup(equipDiscardLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addGroup(equipDiscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(discardButton)
                            .addComponent(equipButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        equipDiscardLayout.setVerticalGroup(
            equipDiscardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(equipDiscardLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(30, 30, 30)
                .addComponent(equipButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(discardButton)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        MainPanel.add(equipDiscard, "equipDiscard");

        jButton11.setText("Yes");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("No");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jLabel15.setText("Congratulations!");

        jLabel16.setText("would you like to save?");

        winText1.setText("You have won this level");

        javax.swing.GroupLayout winPanelLayout = new javax.swing.GroupLayout(winPanel);
        winPanel.setLayout(winPanelLayout);
        winPanelLayout.setHorizontalGroup(
            winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, winPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
            .addGroup(winPanelLayout.createSequentialGroup()
                .addGroup(winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(winPanelLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addGroup(winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winText1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(winPanelLayout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addGroup(winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton11))))
                .addContainerGap(309, Short.MAX_VALUE))
        );
        winPanelLayout.setVerticalGroup(
            winPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(winPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addComponent(winText1)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(41, 41, 41)
                .addComponent(jButton11)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addContainerGap(218, Short.MAX_VALUE))
        );

        MainPanel.add(winPanel, "winPanel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        card.show(MainPanel, "createPanel");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        card.show(MainPanel, "createPanel");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        card.show(MainPanel, "selectPanel");
        List<Hero> heroes;
        heroes = load.createHeros();
    
        String listHeroes = "";
        int i = 1;
        for (Hero hero : heroes) {
            listHeroes += i + ". " +hero.getName() + "\n";
            i++;
        }
        heroList.setEditable(false);
        heroList.setText(listHeroes);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // druid
        String name = inputName.getText();
        if (name != null || name != "")
        {
            myHero = new Druid(name);
            map = new Map(myHero);
            map.newLevel(myHero);

            card.show(MainPanel, "gamePanel");
            Sim.setEditable(false);
            heroStats();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // mage
        String name = inputName.getText();
        if (name != null || name != "")
        {
            myHero = new Mage(name);
            map = new Map(myHero);
            map.newLevel(myHero);

            card.show(MainPanel, "gamePanel");
            Sim.setEditable(false);
            heroStats();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // warrior
        String name = inputName.getText();
        if (name != null || name != "")
        {
            myHero = new Warrior(name);
            map = new Map(myHero);
            map.newLevel(myHero);

            card.show(MainPanel, "gamePanel");
            heroStats();
            Sim.setEditable(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void selectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectButtonActionPerformed
        // selectButton
        int option = Integer.parseInt(selectedHero.getText ());
        List<Hero> heroes;
        heroes = load.createHeros();
        myHero = heroes.get(option - 1);
        map = new Map(myHero);
        map.newLevel(myHero);

        card.show(MainPanel, "gamePanel");
        heroStats();
    }//GEN-LAST:event_selectButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // move up
        map.moveUp();
        checkGuiCollision(myHero);
        heroStats();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // move right
        map.moveRight();
        checkGuiCollision(myHero);
        heroStats();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // move down
        map.moveDown();
        checkGuiCollision(myHero);
        heroStats();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // move left
        map.moveLeft();
        checkGuiCollision(myHero);
        heroStats();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void fightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightButtonActionPerformed
        // if FIGHT is clicked
        //Battle fight = new Battle();
        int fightResult = fight.fight(myHero, foundEnemy);
        if (fightResult == 0) 
        {
            //if you win the fight
            card.show(MainPanel, "equipDiscard");
            System.out.println(fight.droppedArtefact);
            if (fight.droppedArtefact == 1)
            {
                card.show(MainPanel, "equipDiscard");
            }
            map.enemies.remove(foundEnemy);
        } 
        else if (fightResult == 1) 
        {
            //if you win the fight and level up
            if (fight.droppedArtefact == 1)
            {
                card.show(MainPanel, "equipDiscard");
            }
            map.enemies.remove(foundEnemy);
            map.newLevel(myHero);
        }

        card.show(MainPanel, "gamePanel");
        heroStats();
        Sim.setEditable(false);
        Sim.setText(fight.guiFight);
    }//GEN-LAST:event_fightButtonActionPerformed

    private void runButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runButtonActionPerformed
        // if RUN is clicked
        if (fight.run() == -1) 
        {
            if (this.fight.fight(myHero, foundEnemy) == 0)
            {

                map.enemies.remove(foundEnemy);
                if (fight.droppedArtefact == 1)
                {

                    card.show(MainPanel, "equipDiscard");
                }
            }
            else if (this.fight.fight(myHero, foundEnemy) == 1)
            {
                map.enemies.remove(foundEnemy);
                if (fight.droppedArtefact == 1)
                {

                    card.show(MainPanel, "equipDiscard");
                }
                map.newLevel(myHero);
            }
        }

        card.show(MainPanel, "gamePanel");
        heroStats();
        Sim.setEditable(false);
        Sim.setText(fight.guiFight);
    }//GEN-LAST:event_runButtonActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // yes to save
        Writer write = new Writer();
        write.saveHero(myHero);

        card.show(MainPanel, "startPanel");
        map.enemies.clear();
        Sim.setEditable(false);
        Sim.setText("");
        Map.setEditable(false);
        Map.setText("");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // no to not save

        card.show(MainPanel, "startPanel");
        map.enemies.clear();
        Sim.setEditable(false);
        Sim.setText("");
        Map.setEditable(false);
        Map.setText("");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void equipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipButtonActionPerformed
        // Equip item
        card.show(MainPanel, "gamePanel");
    }//GEN-LAST:event_equipButtonActionPerformed

    private void discardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardButtonActionPerformed
        // Discard item
        card.show(MainPanel, "gamePanel");
    }//GEN-LAST:event_discardButtonActionPerformed

    private void heroStats()
    {   
        String stats = "";
        stats += "Name: " + myHero.getName() + "\n";
        stats += "Class: " + myHero.getType() + "\n";
        stats += "Level: " + myHero.getLvl() + "\n";
        stats += "Attack: " + myHero.getAttack() + "\n";
        stats += "Defense: " + myHero.getDefense() + "\n";
        stats += "Health: " + myHero.getHp() + "/" + myHero.getMaxHp() + "\n";
        stats += "Expirience: " + myHero.getXp() + "/" + myHero.neededXP + "\n";
        stats += "Artefact: " + myHero.getArtefact() + "\n";
        stats += "X: " + myHero.getXPos() + "\n";
        stats += "Y: " + myHero.getYPos() + "\n";
        
        gameStats.setEditable(false);
        gameStats.setText(stats);
        enemyPos();
    }
    
    private void enemyPos()
    {
        String stats = "";
        for (Enemy enemy:map.enemies)
        {
            stats += enemy.getName() + "\n";
            stats += "X: " + enemy.getXPos()+ " ";
            stats += "Y: " + enemy.getYPos() + "\n";
        }
        
        Map.setEditable(false);
        Map.setText(stats);
    }
    
    private void checkGuiCollision(Hero hero)
    {
        foundEnemy = null;
        for (Enemy enemy : map.enemies)
        {
            if (enemy.getXPos() == hero.getXPos() && enemy.getYPos() == hero.getYPos()) 
            {
                foundEnemy = enemy;
            }
        }
        if (foundEnemy != null) 
        {

                card.show(MainPanel, "fightRunPanel");
        }
        checkInMap(map, myHero);
    }
    
    public void checkInMap(Map map, Hero hero)
    {
        if (hero.getXPos() < 0 || hero.getXPos() > map.mapX)
        {

            card.show(MainPanel, "winPanel");
        }
        else if (hero.getYPos() < 0 || hero.getYPos() > map.mapY)
        {

            card.show(MainPanel, "winPanel");
        }
    }
    
    public void guiFight(Hero hero, Enemy foundEnemy, Battle fight)
    {
        int fightResult = fight.fight(hero, foundEnemy);
        if (fightResult == 0) 
        {
            //if you win the fight
            map.enemies.remove(foundEnemy);
        } else if (fightResult == 1) 
        {
            //if you win the fight and level up
            map.enemies.remove(foundEnemy);
            map.newLevel(hero);
        }
    }
    
    public void createWindow()
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CreatePanel;
    private javax.swing.JPanel GamePanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JTextPane Map;
    private javax.swing.JPanel SelectPanel;
    private javax.swing.JTextPane Sim;
    private javax.swing.JPanel StartPanel;
    private javax.swing.JButton discardButton;
    private javax.swing.JButton equipButton;
    private javax.swing.JPanel equipDiscard;
    private javax.swing.JButton fightButton;
    private javax.swing.JPanel fightRunPanel;
    private javax.swing.JTextPane gameStats;
    private javax.swing.JTextArea heroList;
    private javax.swing.JLabel heroes;
    private javax.swing.JTextField inputName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton runButton;
    private javax.swing.JButton selectButton;
    private javax.swing.JTextField selectedHero;
    private javax.swing.JPanel winPanel;
    private javax.swing.JTextArea winText;
    private javax.swing.JLabel winText1;
    // End of variables declaration//GEN-END:variables
}
